---
ID: "c2a0c38f-d68b-4f7e-911d-33a3ca3db5f5"
Parent: "38533092-c1b4-42d1-945f-9f48aba9b831"
Template: "e43add4c-eea3-47a1-8271-e64a9fd0a209"
Path: "/sitecore/content/energy-utilities/gridwell/Home/Services"
SharedFields:
- ID: "c7c26117-dbb1-42b2-ab5e-f7223845cca3"
  Hint: __Thumbnail
  Value: |
    <image mediaid="{5704DC6A-EB4D-4306-B7AA-9943110491BA}" />
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "09658d47-362f-410e-b105-3e209c699032"
      Hint: pageSummary
      Value: Gridwell’s services support the safe and reliable operation of the power grid through system coordination, market oversight, and public communication. This page outlines how Gridwell works with communities and partners to maintain grid stability and trust.
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250919T211141Z
    - ID: "3ea35676-87aa-4fb4-8b19-ab47efd870f6"
      Hint: ogImage
      Value: |
        <Image src="https://starter-verticals.sitecoresandbox.cloud/api/public/content/31e7d51faa8f4c49be79a5d041f8a857?v=eca564cd" dam-id="kROJ4I3eTbGS_yxwxaHktg" width="200" height="200" alt="lineworker-on-pole.png" dam-content-type="Other" thumbnailsrc="https://starter-verticals.sitecoresandbox.cloud/api/gateway/70196/thumbnail" />
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Services
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1d3ef3e3-f17d-4fe5-888d-fe3112261a62"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "c8f5c199-4125-4d7a-9764-1cb4495dfd9f"
      Hint: metadataKeywords
      Value: Gridwell services, grid operations, energy market services, power grid coordination, energy reliability
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251216T024235Z
    - ID: "ebaca119-9ba6-4669-9c95-9636c512ff0d"
      Hint: metadataTitle
      Value: Gridwell Services | Powering Reliable Energy Operations
    - ID: "f36e79aa-1a19-431b-8173-f5218760940c"
      Hint: metadataDescription
      Value: Gridwell provides critical services that ensure reliable grid operations, transparent market coordination, and clear public communication. These services support households, businesses, and energy partners across Texas.
    - ID: "fec597dd-3b38-4232-a472-83d725de4d8e"
      Hint: Title
      Value: Services
